package content;


import java.awt.Color;
import java.awt.event.ActionEvent;
import content.Excepciones;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Raquel
 */

public class Ventana extends javax.swing.JFrame{

    DefaultListModel numeros = new DefaultListModel();

    public Ventana() {
        initComponents();
        numeros= new DefaultListModel();
        listNúmeros.setModel(numeros);
        
        this.setLocationRelativeTo(null);
        
        toggleMostrar.setEnabled(false);
        radioLetra.setEnabled(false);
        radioSistemaN.setEnabled(false);
        cmbSistemaN.setEnabled(false);
        listNúmeros.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioLetra = new javax.swing.JRadioButton();
        toggleMostrar = new javax.swing.JToggleButton();
        cmbSistemaN = new javax.swing.JComboBox<>();
        txtNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNúmeros = new javax.swing.JList<>();
        radioSistemaN = new javax.swing.JRadioButton();
        checkOtroFormato = new javax.swing.JCheckBox();
        btnAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioLetra.setText("Letra");
        radioLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLetraActionPerformed(evt);
            }
        });

        toggleMostrar.setText("Mostrar");
        toggleMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleMostrarActionPerformed(evt);
            }
        });

        cmbSistemaN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja un Sistema numérico", "Binario", "Octal", "Hexadecimal" }));

        jScrollPane1.setViewportView(listNúmeros);

        radioSistemaN.setText("Sistema Numérico");
        radioSistemaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSistemaNActionPerformed(evt);
            }
        });

        checkOtroFormato.setText("Escoger otro formato");
        checkOtroFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOtroFormatoActionPerformed(evt);
            }
        });

        btnAñadir.setText("Añadir a la Lista");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese un número decimal del 1-10:");

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("El programa enlista datos numéricos, con la opción de pensonalizar el formato del \nnúmero (a letra u otro sistema numérico). \nEl JToggleButton \"Mostrar\" hace los datos visibles.");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioLetra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioSistemaN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(42, 42, 42))
                                .addComponent(cmbSistemaN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(48, 48, 48)
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkOtroFormato)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(toggleMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(checkOtroFormato)
                                    .addGap(50, 50, 50)
                                    .addComponent(radioLetra)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioSistemaN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbSistemaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkOtroFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOtroFormatoActionPerformed
        radioLetra.setEnabled(true);
        radioSistemaN.setEnabled(true);
    }//GEN-LAST:event_checkOtroFormatoActionPerformed

    private void toggleMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleMostrarActionPerformed
        listNúmeros.setForeground(Color.black);
        if(toggleMostrar.isSelected()==false)listNúmeros.setForeground(Color.white);
    }//GEN-LAST:event_toggleMostrarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
         try{
            String num=txtNumero.getText();  if(txtNumero.getText().isEmpty()){txtNumero.setText(""); throw new Excepciones("Campo vacio");}
        
            for(int i=0; i<num.length(); i++){
            if(txtNumero.getText().charAt(i)<48 || txtNumero.getText().charAt(i)>57){txtNumero.setText(""); throw new Excepciones("Solo un número del 1-10.");}
            }
            int n= Integer.parseInt(txtNumero.getText());
            if(n < 1 || n>10 ){txtNumero.setText(""); throw new Excepciones("Inserte sólo un número del 1-10");}
            
            if(checkOtroFormato.isSelected()==false){numeros.addElement(num);}
            if(radioLetra.isSelected()){
                switch(n){
                    case 1:{numeros.addElement("uno");break;}
                    case 2:{numeros.addElement("dos");break;}
                    case 3:{numeros.addElement("tres");break;}
                    case 4:{numeros.addElement("cuatro");break;}
                    case 5:{numeros.addElement("cinco");break;}
                    case 6:{numeros.addElement("seis");break;}
                    case 7:{numeros.addElement("siete");break;}
                    case 8:{numeros.addElement("ocho");break;}
                    case 9:{numeros.addElement("nueve");break;}
                    case 10:{numeros.addElement("diez");break;}
                }}
            if(cmbSistemaN.getSelectedIndex()!=0){int d = cmbSistemaN.getSelectedIndex();
            if(d==1)switch(n){
                    case 1:{numeros.addElement("0001₂");break;}
                    case 2:{numeros.addElement("0010₂");break;}
                    case 3:{numeros.addElement("0011₂");break;}
                    case 4:{numeros.addElement("0100₂");break;}
                    case 5:{numeros.addElement("0101₂");break;}
                    case 6:{numeros.addElement("0110₂");break;}
                    case 7:{numeros.addElement("0111₂");break;}
                    case 8:{numeros.addElement("1000₂");break;}
                    case 9:{numeros.addElement("1001₂");break;}
                    case 10:{numeros.addElement("1010₂");break;}
                }
            if(d==2)switch(n){//octal
                    case 1:{numeros.addElement("1₈");break;}
                    case 2:{numeros.addElement("2₈");break;}
                    case 3:{numeros.addElement("3₈");break;}
                    case 4:{numeros.addElement("4₈");break;}
                    case 5:{numeros.addElement("5₈");break;}
                    case 6:{numeros.addElement("6₈");break;}
                    case 7:{numeros.addElement("7₈");break;}
                    case 8:{numeros.addElement("10₈");break;}
                    case 9:{numeros.addElement("11₈");break;}
                    case 10:{numeros.addElement("12₈");break;}
                }
            if(d==3)switch(n){//octal
                    case 1:{numeros.addElement("1₁₆");break;}
                    case 2:{numeros.addElement("2₁₆");break;}
                    case 3:{numeros.addElement("3₁₆");break;}
                    case 4:{numeros.addElement("4₁₆");break;}
                    case 5:{numeros.addElement("5₁₆");break;}
                    case 6:{numeros.addElement("6₁₆");break;}
                    case 7:{numeros.addElement("7₁₆");break;}
                    case 8:{numeros.addElement("8₁₆");break;}
                    case 9:{numeros.addElement("9₁₆");break;}
                    case 10:{numeros.addElement("A₁₆");break;}
            }}
            txtNumero.setText("");
            radioLetra.setSelected(false);
            radioSistemaN.setSelected(false);
            checkOtroFormato.setSelected(false);
            radioLetra.setEnabled(false);
            radioSistemaN.setEnabled(false);
            cmbSistemaN.setEnabled(false);
            cmbSistemaN.setSelectedIndex(0);
            if(numeros.size()>0){toggleMostrar.setEnabled(true);}
        }catch(Excepciones e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void radioLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLetraActionPerformed
        radioSistemaN.setEnabled(false);
    }//GEN-LAST:event_radioLetraActionPerformed

    private void radioSistemaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSistemaNActionPerformed
        radioLetra.setEnabled(false);
        cmbSistemaN.setEnabled(true);
    }//GEN-LAST:event_radioSistemaNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JCheckBox checkOtroFormato;
    private javax.swing.JComboBox<String> cmbSistemaN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> listNúmeros;
    private javax.swing.JRadioButton radioLetra;
    private javax.swing.JRadioButton radioSistemaN;
    private javax.swing.JToggleButton toggleMostrar;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
